version: '3.8'
services:
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        container_name: coaster_cloud_web_app_nginx
        ports:
            - 80:8020
        env_file:
            - .env
        volumes:
            - ./:/var/www/html:delegated
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/server.conf:delegated
        networks:
            - local
networks:
    local:
        driver: bridge
