name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/node/Dockerfile
          push: true
          tags: |
            ghcr.io/coaster-cloud/web-app-nginx:latest
        env:
          ANALYTICS_ID: 9c8c9cd9-9625-4083-b05e-ab8f8acd7743
          DATA_SERVICE_URL: https://data.coaster.cloud/v1
          SENTRY_DSN: https://e5547154090e45bba96718e5bf78b28e@o320437.ingest.sentry.io/5517128
