name: release

on:
  push:
    tags: ['*']

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Save tag version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Create env file
        run: |
          touch .env
          echo ANALYTICS_ID=${{ secrets.ANALYTICS_ID }} >> .env
          echo DATA_SERVICE_URL=${{ secrets.DATA_SERVICE_URL }} >> .env
          echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> .env
          echo APP_VERSION=${{ steps.vars.outputs.tag }} >> .env

      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/node/Dockerfile
          push: true
          tags: |
            ghcr.io/coaster-cloud/web-app-nginx:latest
            ghcr.io/coaster-cloud/web-app-nginx:${{ steps.vars.outputs.tag }}
